### ISSUE TITLE
Warning message that should not be

### ISSUE THREAD

**Issue by JFCote** [Tufin/oasdiff-action#6]
Hi!

I'm integrating your github action in my workflow.

When I provide this in my workflow:

```
      - name: Running OpenAPI Spec diff action
        id: test_breaking_changes
        uses: Tufin/oasdiff-action@v2.1.0
        with:
          base: 'openapi.old.yaml'
          revision: 'openapi.yaml'
          format: 'text'
          check-breaking: true
          fail-on-diff: true
```

I have this in the log of the action:

```
Warning: Unexpected input(s) 'check-breaking', valid inputs are ['entryPoint', 'args', 'base', 'revision', 'format', 'breaking-only', 'fail-on-diff']
Run Tufin/oasdiff-action@v[2](https://github.com/floevcharging/CPO.ChargingStation.Service/actions/runs/4874879584/jobs/8696363534?pr=86#step:6:2).1.0
  with:
    base: openapi.old.yaml
    revision: openapi.yaml
    format: text
    check-breaking: true
    fail-on-diff: true
    breaking-only: false
```

`check-breaking` is considered "unexpected" when it is supposed to be the new command based on the documentation and you can see the added "breaking-only".

Expected behavior:

No warning and not "breaking-only" parameter passed.

Other than that, it seems to work perfectly, thank you!
