### ISSUE TITLE
Error: unknown command "text" for "oasdiff"

### ISSUE THREAD

**Issue by mleczakm** [Tufin/oasdiff-action#9]
I'm unable to run action with config like this:
```
      - name: Running OpenAPI Spec diff action
        id: test_breaking_changes
        uses: Tufin/oasdiff-action@v2
        with:
          base: 'head/combinedSchema.json'
          revision: 'base/combinedSchema.json'
          format: text
          breaking-only: true
          fail-on-diff: true
```
it fails with error: 
```
running breaking_only and fail_on_diff...
Error: unknown command "text" for "oasdiff"
Run 'oasdiff --help' for usage.
```
